stages:
  - build
  - test
  - deploy

# Build Stage
build:
  stage: build
  image: node:18
  script:
    - echo "Testing Shell Executor"
    - node --version || echo "Node.js not found"
    - npm --version || echo "npm not found"
    - npm --version
    - npx --version
    - npm ci
    - npm run build
  artifacts:
    paths:
      - build/
    expire_in: 1 week

test:
  stage: test
  script:
    - npx cypress run

docker-build:
  stage: deploy
  script:
    - docker stop tweetle-app-staging || true
    - docker rm tweetle-app-staging || true
    - docker build -t tweetle-app .
    - docker run --env-file .env -d --name=tweetle-app-staging --network=tweetle-network -p 3000:3000 tweetle-app
  only:
    - main
