stages:
  - build
  - test
  - deploy

# Build Stage
build:
  stage: build
  script:
    - npm ci
    - npm run build

# Test Stage
test:
  stage: test
  script:
    - npm ci
    - npm run build
    - npx cypress run

deploy:
  stage: deploy
  script:
    # Stop and remove the existing container if it exists
    - if [ "$(docker ps -aq -f name=tweetle-app)" ]; then docker rm -f tweetle-app; fi

    # Remove the old image if it exists
    - if [ "$(docker images -q tweetle-app)" ]; then docker rmi tweetle-app; fi

    # Build the Docker image
    - docker build -t tweetle-app .

    # Run the new container
    - docker run -d -p 3000:3000 --name tweetle-app tweetle-app
